#
#!/bin/bash
#.screenlayout scripts generated by arandr
#

HDMI_VIDEO_SCRIPT="/home/ryan/.screenlayout/1080-hdmi.sh"

# If HDMI1 monitor is active, turn it off
if xrandr --listactivemonitors | grep -q "HDMI1"
    then
        echo "turning off hdmi output"
        sh /home/ryan/.screenlayout/no-hdmi.sh
    
# If HDMI1 monitor is inacive, turn it on
    else
        echo "turning on hdmi output"
        sh "$HDMI_VIDEO_SCRIPT"
fi

# Restart i3 window manager
i3-msg restart

